<style>
.popup{
    background-color: #efc;
    height: 50px;
    box-shadow: 0px 2px 2px #aaa;
    padding: 10px;
}
.close {
    color: #000;
    float: right;
    font-size: 28px;
    font-weight: bold;
}
ul.social li{
	display: inline-block;
    padding: 0px 20px;
}
ul.social li a{
	text-decoration: none;
	font-size: 18px
}
</style>
<a class="link-copyright" href="http://magento.com" target="_blank" title="<?php /* @escapeNotVerified */ echo __('Magento') ?>"></a>
<?php /* @escapeNotVerified */ echo __('Copyright &copy; %1 Magento Commerce Inc. All rights reserved.', date('Y')) ?>
<?php if($block->isProductPage() && $block->isSaved()): ?>
<div style="    background-color: #efc;
    width: 400px;
    margin: auto;
    height: 50px;
    padding: 6px 11px;
    position: absolute;
    top: 70px;
    left: 30%;">
	<ul class="social">
		<?php
			$idd = $this->getRequest()->getParam('id');
			$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
			$product = $objectManager->create('Magento\Catalog\Model\Product')->load($idd);
			$product_url = $product->getData()['url_key'];
			$ser_add =  $_SERVER["SERVER_ADDR"];
		?>
		
		<span>Share this product on</span>
		<iframe src="https://www.facebook.com/plugins/share_button.php?href=http%3A%2F%2F<?php echo $ser_add;?>/mage2/<?php echo $product_url;?>.html&layout=button&size=small&mobile_iframe=true&width=59&height=20&appId" width="59" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
		<a class="twitter-share-button"
	      href="https://twitter.com/intent/tweet?text=Latest%20Products?"><link rel="canonical"
  			href="http://<?php echo $ser_add;?>/mage2/<?php echo $product_url;?>.html">Tweet</a>
	    <script src="https://platform.linkedin.com/in.js" type="text/javascript"> lang: en_US</script>
		<script type="IN/Share" data-url="http://<?php echo $ser_add;?>/mage2/<?php echo $product_url;?>.html"></script>
	</ul>
</div>
<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>
<?php endif;?>